// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Neo.AgentOrchestration.Infrastructure.Persistence;

#nullable disable

namespace Neo.AgentOrchestration.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrchestrationDbContext))]
    [Migration("20260926172705_InitialOrchestration")]
    partial class InitialOrchestration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Agents.AgentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Instructions")
                        .HasMaxLength(32000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("RoleProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SkillPath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Key")
                        .IsUnique();

                    b.HasIndex("RoleProfileId", "WorkspaceId", "OrganizationId");

                    b.ToTable("AgentProfiles", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Agents.RoleProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ScopeDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Key")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "OrganizationId");

                    b.ToTable("RoleProfiles", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Projects.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Organizations", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Key")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "OrganizationId");

                    b.ToTable("Projects", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Projects.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Key")
                        .IsUnique();

                    b.ToTable("Workspaces", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Branch")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(32000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<long?>("EstimatedSeconds")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerAgentId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerChatId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("OwnerRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentWorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerRoleId")
                        .IsUnique()
                        .HasFilter("[Status] = 3 AND [OwnerRoleId] IS NOT NULL");

                    b.HasIndex("ParentWorkItemId", "ProjectId");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.HasIndex("OwnerRoleId", "WorkspaceId", "OrganizationId");

                    b.HasIndex("ProjectId", "WorkspaceId", "OrganizationId");

                    b.HasIndex("WorkspaceId", "ProjectId", "Domain", "Status");

                    b.ToTable("WorkItems", "nao", t =>
                        {
                            t.HasCheckConstraint("CK_WorkItems_Estimate", "[EstimatedSeconds] IS NULL OR [EstimatedSeconds] > 0");

                            t.HasCheckConstraint("CK_WorkItems_Owner", "([OwnerRoleId] IS NULL AND [OwnerAgentId] IS NULL AND [OwnerChatId] IS NULL AND [Status] <> 3) OR ([OwnerRoleId] IS NOT NULL AND [OwnerAgentId] IS NOT NULL AND [OwnerChatId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_WorkItems_Parent", "[ParentWorkItemId] IS NULL OR [ParentWorkItemId] <> [Id]");

                            t.HasCheckConstraint("CK_WorkItems_Status", "[Status] BETWEEN 1 AND 7 AND [Priority] BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItemDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DependsOnWorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnWorkItemId", "ProjectId");

                    b.HasIndex("WorkItemId", "DependsOnWorkItemId")
                        .IsUnique();

                    b.HasIndex("WorkItemId", "ProjectId");

                    b.ToTable("WorkItemDependencies", "nao", t =>
                        {
                            t.HasCheckConstraint("CK_Dependency_Self", "[WorkItemId] <> [DependsOnWorkItemId]");
                        });
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItemEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Details")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Outcome")
                        .HasColumnType("tinyint");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemId", "Sequence")
                        .IsUnique();

                    b.ToTable("WorkItemEvidence", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItemLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemId", "CreatedAtUtc");

                    b.ToTable("WorkItemLogs", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItemTimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DurationSeconds")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemId")
                        .IsUnique()
                        .HasFilter("[EndedAtUtc] IS NULL");

                    b.ToTable("WorkItemTimeEntries", "nao", t =>
                        {
                            t.HasCheckConstraint("CK_Time_Duration", "[DurationSeconds] >= 0 AND ([EndedAtUtc] IS NULL OR [EndedAtUtc] >= [StartedAtUtc])");
                        });
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Workflows.WorkflowApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewerAgentId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReviewerChatId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TransitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkItemVersion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkflowVersion")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransitionId", "WorkflowDefinitionId");

                    b.HasIndex("WorkItemId", "ProjectId");

                    b.HasIndex("WorkflowDefinitionId", "ProjectId");

                    b.HasIndex("WorkItemId", "WorkItemVersion", "WorkflowVersion");

                    b.ToTable("WorkflowApprovals", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Workflows.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.HasIndex("ProjectId", "WorkspaceId", "OrganizationId");

                    b.ToTable("WorkflowDefinitions", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Workflows.WorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FromRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("FromStatus")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequireApproval")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireCommit")
                        .HasColumnType("bit");

                    b.Property<bool>("RequirePassingTests")
                        .HasColumnType("bit");

                    b.Property<string>("RequiredArtifact")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("ToRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ToStatus")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId", "Key")
                        .IsUnique();

                    b.HasIndex("FromRoleId", "WorkspaceId", "OrganizationId");

                    b.HasIndex("ToRoleId", "WorkspaceId", "OrganizationId");

                    b.HasIndex("WorkflowDefinitionId", "FromRoleId", "FromStatus")
                        .IsUnique()
                        .HasFilter("[IsEnabled] = 1");

                    b.HasIndex("WorkflowDefinitionId", "WorkspaceId", "OrganizationId");

                    b.ToTable("WorkflowTransitions", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Agents.AgentProfile", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Agents.RoleProfile", null)
                        .WithMany()
                        .HasForeignKey("RoleProfileId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Agents.RoleProfile", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Projects.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Projects.Project", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Projects.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Projects.Workspace", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Projects.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItem", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Work.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("ParentWorkItemId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Neo.AgentOrchestration.Domain.Agents.RoleProfile", null)
                        .WithMany()
                        .HasForeignKey("OwnerRoleId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Neo.AgentOrchestration.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItemDependency", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Work.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("DependsOnWorkItemId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neo.AgentOrchestration.Domain.Work.WorkItem", null)
                        .WithMany("Dependencies")
                        .HasForeignKey("WorkItemId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItemEvidence", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Work.WorkItem", null)
                        .WithMany("Evidence")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItemLog", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Work.WorkItem", null)
                        .WithMany("Logs")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItemTimeEntry", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Work.WorkItem", null)
                        .WithMany("TimeEntries")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Workflows.WorkflowApproval", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Workflows.WorkflowTransition", null)
                        .WithMany()
                        .HasForeignKey("TransitionId", "WorkflowDefinitionId")
                        .HasPrincipalKey("Id", "WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neo.AgentOrchestration.Domain.Work.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("WorkItemId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neo.AgentOrchestration.Domain.Workflows.WorkflowDefinition", null)
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Workflows.WorkflowDefinition", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Workflows.WorkflowTransition", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Agents.RoleProfile", null)
                        .WithMany()
                        .HasForeignKey("FromRoleId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neo.AgentOrchestration.Domain.Agents.RoleProfile", null)
                        .WithMany()
                        .HasForeignKey("ToRoleId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Neo.AgentOrchestration.Domain.Workflows.WorkflowDefinition", null)
                        .WithMany("Transitions")
                        .HasForeignKey("WorkflowDefinitionId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItem", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Evidence");

                    b.Navigation("Logs");

                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Workflows.WorkflowDefinition", b =>
                {
                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
