// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Neo.AgentOrchestration.Infrastructure.Persistence;

#nullable disable

namespace Neo.AgentOrchestration.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrchestrationDbContext))]
    [Migration("20261009001421_WorkItemTokenMetering")]
    partial class WorkItemTokenMetering
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Agents.AgentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Instructions")
                        .HasMaxLength(32000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("RoleProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SkillPath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Key")
                        .IsUnique();

                    b.HasIndex("RoleProfileId", "WorkspaceId", "OrganizationId");

                    b.ToTable("AgentProfiles", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Agents.RoleProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("MaxConcurrentWorkItems")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ScopeDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Key")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "OrganizationId");

                    b.ToTable("RoleProfiles", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Projects.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Organizations", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Key")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "OrganizationId");

                    b.ToTable("Projects", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Projects.ProjectRepositoryBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CiCdReference")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DevelopmentBranch")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("RepositoryKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecretReference")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "ProjectId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.HasIndex("ProjectId", "WorkspaceId", "OrganizationId");

                    b.ToTable("ProjectRepositoryBindings", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Projects.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Key")
                        .IsUnique();

                    b.ToTable("Workspaces", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Runs.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowExternalExecution")
                        .HasColumnType("bit");

                    b.Property<string>("Branch")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("Decision")
                        .HasColumnType("tinyint");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("HarnessBinding")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("HarnessPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hop")
                        .HasColumnType("int");

                    b.Property<Guid>("InitialWorkflowVersion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Instructions")
                        .HasMaxLength(32000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("NextRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PreviousRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid?>("RepositoryBindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RepositoryDefaultBranch")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RepositoryDevelopmentBranch")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RepositoryKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RepositoryUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RequestedByAgentId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RequestedByChatId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ResultSummary")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("SimulationOutcome")
                        .HasColumnType("tinyint");

                    b.Property<string>("SkillPath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkItemVersion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkflowVersion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PreviousRunId")
                        .IsUnique()
                        .HasFilter("[PreviousRunId] IS NOT NULL");

                    b.HasIndex("WorkItemId")
                        .IsUnique()
                        .HasFilter("[Status] IN (1, 2)");

                    b.HasIndex("WorkItemId", "ProjectId");

                    b.HasIndex("WorkflowId", "ProjectId");

                    b.HasIndex("PreviousRunId", "WorkItemId", "ProjectId");

                    b.HasIndex("ProjectId", "WorkspaceId", "OrganizationId");

                    b.HasIndex("AgentProfileId", "RoleId", "WorkspaceId", "OrganizationId");

                    b.ToTable("AgentRuns", "nao", t =>
                        {
                            t.HasCheckConstraint("CK_AgentRuns_Hop", "[Hop] BETWEEN 1 AND 20 AND ([PreviousRunId] IS NULL OR [PreviousRunId] <> [Id])");

                            t.HasCheckConstraint("CK_AgentRuns_Status", "[Status] BETWEEN 1 AND 5 AND [Decision] BETWEEN 0 AND 4 AND [SimulationOutcome] BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Runs.TokenUsageReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("CachedInputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<long?>("ReasoningTokens")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "WorkItemId", "AgentRunId");

                    b.HasIndex("AgentRunId", "WorkItemId");

                    b.HasIndex("OrganizationId", "WorkspaceId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "WorkspaceId", "AgentRunId", "RecordedAtUtc");

                    b.ToTable("TokenUsageReports", "nao", t =>
                        {
                            t.HasCheckConstraint("CK_TokenUsageReports_Counts", "([InputTokens] IS NULL OR [InputTokens] >= 0) AND ([OutputTokens] IS NULL OR [OutputTokens] >= 0) AND ([CachedInputTokens] IS NULL OR [CachedInputTokens] >= 0) AND ([ReasoningTokens] IS NULL OR [ReasoningTokens] >= 0)");
                        });
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Templates.ProjectTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByAgent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreatedByChat")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasMaxLength(64000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Revision")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "OrganizationId");

                    b.HasIndex("WorkspaceId", "Key", "Revision")
                        .IsUnique();

                    b.ToTable("ProjectTemplates", "nao", t =>
                        {
                            t.HasCheckConstraint("CK_Template_Revision", "[Revision] > 0");
                        });
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Templates.TemplateInstantiation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedByAgent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreatedByChat")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("MappingJson")
                        .IsRequired()
                        .HasMaxLength(40000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasMaxLength(40000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "RequestId")
                        .IsUnique();

                    b.HasIndex("ProjectId", "WorkspaceId", "OrganizationId");

                    b.HasIndex("TemplateId", "WorkspaceId", "OrganizationId");

                    b.ToTable("TemplateInstantiations", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcceptanceCriteria")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Branch")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(32000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<long?>("EstimatedSeconds")
                        .HasColumnType("bigint");

                    b.Property<long?>("EstimatedTokens")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerAgentId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerChatId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("OwnerRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentWorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerRoleId")
                        .HasFilter("[Status] = 3 AND [OwnerRoleId] IS NOT NULL");

                    b.HasIndex("ParentWorkItemId", "ProjectId");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.HasIndex("OwnerRoleId", "WorkspaceId", "OrganizationId");

                    b.HasIndex("ProjectId", "WorkspaceId", "OrganizationId");

                    b.HasIndex("WorkspaceId", "ProjectId", "Domain", "Status");

                    b.ToTable("WorkItems", "nao", t =>
                        {
                            t.HasCheckConstraint("CK_WorkItems_Estimate", "[EstimatedSeconds] IS NULL OR [EstimatedSeconds] > 0");

                            t.HasCheckConstraint("CK_WorkItems_Owner", "([OwnerRoleId] IS NULL AND [OwnerAgentId] IS NULL AND [OwnerChatId] IS NULL AND [Status] <> 3) OR ([OwnerRoleId] IS NOT NULL AND [OwnerAgentId] IS NOT NULL AND [OwnerChatId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_WorkItems_Parent", "[ParentWorkItemId] IS NULL OR [ParentWorkItemId] <> [Id]");

                            t.HasCheckConstraint("CK_WorkItems_Status", "[Status] BETWEEN 1 AND 7 AND [Priority] BETWEEN 1 AND 4");

                            t.HasCheckConstraint("CK_WorkItems_TokenEstimate", "[EstimatedTokens] IS NULL OR [EstimatedTokens] > 0");

                            t.HasCheckConstraint("CK_WorkItems_Type", "[Type] BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItemDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DependsOnWorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnWorkItemId", "ProjectId");

                    b.HasIndex("WorkItemId", "DependsOnWorkItemId")
                        .IsUnique();

                    b.HasIndex("WorkItemId", "ProjectId");

                    b.ToTable("WorkItemDependencies", "nao", t =>
                        {
                            t.HasCheckConstraint("CK_Dependency_Self", "[WorkItemId] <> [DependsOnWorkItemId]");
                        });
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItemEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Details")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Outcome")
                        .HasColumnType("tinyint");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemId", "Sequence")
                        .IsUnique();

                    b.ToTable("WorkItemEvidence", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItemLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemId", "CreatedAtUtc");

                    b.ToTable("WorkItemLogs", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItemOwnerHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OriginalStatus")
                        .HasColumnType("int");

                    b.Property<string>("OwnerAgent")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerChat")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerRole")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SourceWorkItemId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemId", "ProjectId");

                    b.HasIndex("ProjectId", "WorkItemId", "CreatedAtUtc");

                    b.ToTable("WorkItemOwnerHistory", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItemTimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DurationSeconds")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemId")
                        .IsUnique()
                        .HasFilter("[EndedAtUtc] IS NULL");

                    b.ToTable("WorkItemTimeEntries", "nao", t =>
                        {
                            t.HasCheckConstraint("CK_Time_Duration", "[DurationSeconds] >= 0 AND ([EndedAtUtc] IS NULL OR [EndedAtUtc] >= [StartedAtUtc])");
                        });
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkTokenUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("CachedInputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<long?>("ReasoningTokens")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemId", "RecordedAtUtc");

                    b.ToTable("WorkTokenUsage", "nao", t =>
                        {
                            t.HasCheckConstraint("CK_WorkTokenUsage_Counts", "([InputTokens] IS NULL OR [InputTokens] >= 0) AND ([OutputTokens] IS NULL OR [OutputTokens] >= 0) AND ([CachedInputTokens] IS NULL OR [CachedInputTokens] >= 0) AND ([ReasoningTokens] IS NULL OR [ReasoningTokens] >= 0) AND ([InputTokens] IS NULL OR [CachedInputTokens] IS NULL OR [CachedInputTokens] <= [InputTokens]) AND ([OutputTokens] IS NULL OR [ReasoningTokens] IS NULL OR [ReasoningTokens] <= [OutputTokens]) AND ([InputTokens] IS NOT NULL OR [OutputTokens] IS NOT NULL OR [CachedInputTokens] IS NOT NULL OR [ReasoningTokens] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Workflows.WorkflowApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewerAgentId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReviewerChatId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TransitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkItemVersion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkflowVersion")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransitionId", "WorkflowDefinitionId");

                    b.HasIndex("WorkItemId", "ProjectId");

                    b.HasIndex("WorkflowDefinitionId", "ProjectId");

                    b.HasIndex("WorkItemId", "WorkItemVersion", "WorkflowVersion");

                    b.ToTable("WorkflowApprovals", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Workflows.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.HasIndex("ProjectId", "WorkspaceId", "OrganizationId");

                    b.ToTable("WorkflowDefinitions", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Workflows.WorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FromRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("FromStatus")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequireApproval")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireCommit")
                        .HasColumnType("bit");

                    b.Property<bool>("RequirePassingTests")
                        .HasColumnType("bit");

                    b.Property<string>("RequiredArtifact")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("ToRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ToStatus")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId", "Key")
                        .IsUnique();

                    b.HasIndex("FromRoleId", "WorkspaceId", "OrganizationId");

                    b.HasIndex("ToRoleId", "WorkspaceId", "OrganizationId");

                    b.HasIndex("WorkflowDefinitionId", "FromRoleId", "FromStatus")
                        .IsUnique()
                        .HasFilter("[IsEnabled] = 1");

                    b.HasIndex("WorkflowDefinitionId", "WorkspaceId", "OrganizationId");

                    b.ToTable("WorkflowTransitions", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Infrastructure.Delivery.DeliveryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgentRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("OutboxId")
                        .HasColumnType("bigint");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkItemVersion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OutboxId")
                        .IsUnique();

                    b.HasIndex("WorkItemId", "ProjectId");

                    b.HasIndex("AgentRunId", "WorkItemId", "ProjectId");

                    b.HasIndex("ProjectId", "WorkspaceId", "OrganizationId");

                    b.HasIndex("WorkspaceId", "Source", "MessageId")
                        .IsUnique();

                    b.ToTable("Deliveries", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Infrastructure.Delivery.InboxReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("FollowUpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkItemVersion")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemId", "ProjectId");

                    b.HasIndex("FollowUpId", "WorkItemId", "ProjectId");

                    b.HasIndex("ProjectId", "WorkspaceId", "OrganizationId");

                    b.HasIndex("WorkspaceId", "Source", "MessageId")
                        .IsUnique();

                    b.ToTable("InboxReceipts", "nao");
                });

            modelBuilder.Entity("Neo.Domain.Entities.Common.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeliveryLeaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeliveryLeaseUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobId")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("MessageResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("OutboxState")
                        .HasColumnType("int");

                    b.Property<string>("ProcessError")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ProcessTryCount")
                        .HasColumnType("int");

                    b.Property<string>("PublishError")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PublishTryCount")
                        .HasColumnType("int");

                    b.Property<string>("TenantKey")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("TenantKey", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[TenantKey] IS NOT NULL AND [IdempotencyKey] IS NOT NULL");

                    b.HasIndex("OutboxState", "NextAttemptAtUtc", "DeliveryLeaseUntilUtc");

                    b.ToTable("OutboxMessages", "nao");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Agents.AgentProfile", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Agents.RoleProfile", null)
                        .WithMany()
                        .HasForeignKey("RoleProfileId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Agents.RoleProfile", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Projects.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Projects.Project", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Projects.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Projects.ProjectRepositoryBinding", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Projects.Workspace", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Projects.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Runs.AgentRun", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Work.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("WorkItemId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neo.AgentOrchestration.Domain.Workflows.WorkflowDefinition", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neo.AgentOrchestration.Domain.Runs.AgentRun", null)
                        .WithMany()
                        .HasForeignKey("PreviousRunId", "WorkItemId", "ProjectId")
                        .HasPrincipalKey("Id", "WorkItemId", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Neo.AgentOrchestration.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neo.AgentOrchestration.Domain.Agents.AgentProfile", null)
                        .WithMany()
                        .HasForeignKey("AgentProfileId", "RoleId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "RoleProfileId", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Runs.TokenUsageReport", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Runs.AgentRun", null)
                        .WithMany()
                        .HasForeignKey("AgentRunId", "WorkItemId")
                        .HasPrincipalKey("Id", "WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Templates.ProjectTemplate", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Projects.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Templates.TemplateInstantiation", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neo.AgentOrchestration.Domain.Templates.ProjectTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplateId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItem", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Work.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("ParentWorkItemId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Neo.AgentOrchestration.Domain.Agents.RoleProfile", null)
                        .WithMany()
                        .HasForeignKey("OwnerRoleId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Neo.AgentOrchestration.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItemDependency", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Work.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("DependsOnWorkItemId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neo.AgentOrchestration.Domain.Work.WorkItem", null)
                        .WithMany("Dependencies")
                        .HasForeignKey("WorkItemId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItemEvidence", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Work.WorkItem", null)
                        .WithMany("Evidence")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItemLog", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Work.WorkItem", null)
                        .WithMany("Logs")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItemOwnerHistory", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Work.WorkItem", null)
                        .WithMany("OwnerHistory")
                        .HasForeignKey("WorkItemId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItemTimeEntry", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Work.WorkItem", null)
                        .WithMany("TimeEntries")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkTokenUsage", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Work.WorkItem", null)
                        .WithMany("TokenUsage")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Workflows.WorkflowApproval", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Workflows.WorkflowTransition", null)
                        .WithMany()
                        .HasForeignKey("TransitionId", "WorkflowDefinitionId")
                        .HasPrincipalKey("Id", "WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neo.AgentOrchestration.Domain.Work.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("WorkItemId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neo.AgentOrchestration.Domain.Workflows.WorkflowDefinition", null)
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Workflows.WorkflowDefinition", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Workflows.WorkflowTransition", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Agents.RoleProfile", null)
                        .WithMany()
                        .HasForeignKey("FromRoleId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neo.AgentOrchestration.Domain.Agents.RoleProfile", null)
                        .WithMany()
                        .HasForeignKey("ToRoleId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Neo.AgentOrchestration.Domain.Workflows.WorkflowDefinition", null)
                        .WithMany("Transitions")
                        .HasForeignKey("WorkflowDefinitionId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Infrastructure.Delivery.DeliveryRecord", b =>
                {
                    b.HasOne("Neo.Domain.Entities.Common.OutboxMessage", "Outbox")
                        .WithOne()
                        .HasForeignKey("Neo.AgentOrchestration.Infrastructure.Delivery.DeliveryRecord", "OutboxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neo.AgentOrchestration.Domain.Work.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("WorkItemId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neo.AgentOrchestration.Domain.Runs.AgentRun", null)
                        .WithMany()
                        .HasForeignKey("AgentRunId", "WorkItemId", "ProjectId")
                        .HasPrincipalKey("Id", "WorkItemId", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Neo.AgentOrchestration.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Outbox");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Infrastructure.Delivery.InboxReceipt", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.Work.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("WorkItemId", "ProjectId")
                        .HasPrincipalKey("Id", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neo.AgentOrchestration.Infrastructure.Delivery.DeliveryRecord", "FollowUp")
                        .WithMany()
                        .HasForeignKey("FollowUpId", "WorkItemId", "ProjectId")
                        .HasPrincipalKey("Id", "WorkItemId", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Neo.AgentOrchestration.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId", "WorkspaceId", "OrganizationId")
                        .HasPrincipalKey("Id", "WorkspaceId", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FollowUp");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Work.WorkItem", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Evidence");

                    b.Navigation("Logs");

                    b.Navigation("OwnerHistory");

                    b.Navigation("TimeEntries");

                    b.Navigation("TokenUsage");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.Workflows.WorkflowDefinition", b =>
                {
                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
