// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Neo.AgentOrchestration.Infrastructure.ExternalExecution;

#nullable disable

namespace Neo.AgentOrchestration.Infrastructure.ExternalExecution.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20261009095030_GatewayDurableActivation")]
    partial class GatewayDurableActivation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Neo.AgentOrchestration.Domain.ExternalExecution.GatewayRun", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ApprovalPending")
                        .HasColumnType("bit");

                    b.Property<string>("BindingFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("BindingKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid?>("CallbackReceiptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CapacityHeld")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FrozenResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("LeaseUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<string>("PreparedHandle")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SandboxId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("StopPending")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RunId");

                    b.HasIndex("CapacityHeld", "LeaseUntilUtc", "Phase");

                    b.ToTable("Runs", "gateway");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Infrastructure.ExternalExecution.GatewayActivation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("OutboxId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OutboxId")
                        .IsUnique();

                    b.HasIndex("RunId", "Sequence")
                        .IsUnique();

                    b.HasIndex("RunId", "OrganizationId", "WorkspaceId", "ProjectId");

                    b.ToTable("Activations", "gateway");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Infrastructure.ExternalExecution.GatewayUsageEntry", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReportId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RunId", "ReportId");

                    b.HasIndex("RunId", "OrganizationId", "WorkspaceId", "ProjectId");

                    b.ToTable("Usage", "gateway");
                });

            modelBuilder.Entity("Neo.Domain.Entities.Common.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeliveryLeaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeliveryLeaseUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobId")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("MessageResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("OutboxState")
                        .HasColumnType("int");

                    b.Property<string>("ProcessError")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ProcessTryCount")
                        .HasColumnType("int");

                    b.Property<string>("PublishError")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PublishTryCount")
                        .HasColumnType("int");

                    b.Property<string>("TenantKey")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("TenantKey", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[TenantKey] IS NOT NULL AND [IdempotencyKey] IS NOT NULL");

                    b.HasIndex("OutboxState", "NextAttemptAtUtc", "DeliveryLeaseUntilUtc");

                    b.ToTable("OutboxMessages", "gateway");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Infrastructure.ExternalExecution.GatewayActivation", b =>
                {
                    b.HasOne("Neo.Domain.Entities.Common.OutboxMessage", "Outbox")
                        .WithOne()
                        .HasForeignKey("Neo.AgentOrchestration.Infrastructure.ExternalExecution.GatewayActivation", "OutboxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Neo.AgentOrchestration.Domain.ExternalExecution.GatewayRun", null)
                        .WithMany()
                        .HasForeignKey("RunId", "OrganizationId", "WorkspaceId", "ProjectId")
                        .HasPrincipalKey("RunId", "OrganizationId", "WorkspaceId", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Outbox");
                });

            modelBuilder.Entity("Neo.AgentOrchestration.Infrastructure.ExternalExecution.GatewayUsageEntry", b =>
                {
                    b.HasOne("Neo.AgentOrchestration.Domain.ExternalExecution.GatewayRun", null)
                        .WithMany()
                        .HasForeignKey("RunId", "OrganizationId", "WorkspaceId", "ProjectId")
                        .HasPrincipalKey("RunId", "OrganizationId", "WorkspaceId", "ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
