<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design"><PrivateAssets>all</PrivateAssets></PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Neo.AgentOrchestration.Application/Neo.AgentOrchestration.Application.csproj" />
    <ProjectReference Include="$(NeoRoot)/src/Neo.Infrastructure/Neo.Infrastructure.csproj" />
  </ItemGroup>
</Project>
