<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>10.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <!--<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />-->
	<!--<PackageReference Include="Hangfire.Pro" />
    <PackageReference Include="Hangfire.Pro.Redis" />
    <PackageReference Include="Hangfire.Tags.Pro.Redis" />
    <PackageReference Include="Hangfire.Throttling"  />
    <PackageReference Include="Hangfire.AspNetCore.Plus" />-->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Neo.Application\Neo.Application.csproj" />
    <ProjectReference Include="..\Neo.Domain\Neo.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.SourceLink.GitHub">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>