<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>10.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Castle.Core" />
    <PackageReference Include="MediatR" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
</ItemGroup>
<ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Neo.Common\Neo.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.SourceLink.GitHub">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>